name: Check for broken links

# https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

on:
  pull_request:

jobs:
  markdown-link-check:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run linkspector
      uses: umbrelladocs/action-linkspector@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        fail_level: any